# Generated by Django 4.0.4 on 2022-05-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='portfolio_images')),
                ('image_caption', models.CharField(max_length=100)),
            ],
        ),
    ]
