# Generated by Django 4.0.4 on 2022-07-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_portfolioimages_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimages',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
