# Generated by Django 4.0.4 on 2022-07-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_portfolioimages_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimages',
            name='link',
        ),
    ]
